import { defineHSeion, type HiraganaSeion } from '../core';

export const HIRAGANA_SEION: Record<string, HiraganaSeion> = {
  // --- A 行 ---
  あ: defineHSeion({
    id: 'h-a',
    kana: 'あ',
    romaji: 'a',
    kanaKanjiOrigin: '安', // 平假名的汉字来源

    word: '愛', // 一定是汉字词或者是包含汉字的词，要求尽可能简单易学，最好是名词，发音中对未学假名的数量不宜过多。总体需符合日语入门人群的水平。
    wordKana: 'あい',
    wordRomaji: 'a·i',
    wordMeaning: { en: 'love', zh: '爱', zhHant: '愛' },

    wordEmoji: '❤️', // 该单词尽可能是简单名词，有对应的 emoji
    kanaDistractors: ['お', 'め', 'ぬ'], // 该假名的形近
    romajiDistractors: ['o', 'ou', 'au'], // 该假名的音近
    wordDistractors: ['あえ', 'めい', 'おい'], // 与 wordKana 的形似
  }),

  い: defineHSeion({
    id: 'h-i',
    kana: 'い',
    romaji: 'i',
    kanaKanjiOrigin: '以',

    word: '家',
    wordKana: 'いえ',
    wordRomaji: 'i·e',
    wordMeaning: { en: 'house', zh: '房子', zhHant: '房子' },

    wordEmoji: '🏠',
    kanaDistractors: ['り', 'こ', 'に'],
    romajiDistractors: ['e', 'ei', 'ie'],
    wordDistractors: ['にえ', 'えい', 'りえ'],
  }),

  う: defineHSeion({
    id: 'h-u',
    kana: 'う',
    romaji: 'u',
    kanaKanjiOrigin: '宇',

    word: '上',
    wordKana: 'うえ',
    wordRomaji: 'u·e',
    wordMeaning: { en: 'up; superior', zh: '上面', zhHant: '上面' },

    wordEmoji: '☝️',
    kanaDistractors: ['え', 'ラ', 'ら'],
    romajiDistractors: ['wu', 'eu', 'ui'],
    wordDistractors: ['うら', 'えう', 'ラら', 'ラえ'],
  }),

  え: defineHSeion({
    id: 'h-e',
    kana: 'え',
    romaji: 'e',
    kanaKanjiOrigin: '衣',
    word: '絵',
    wordKana: 'え',
    wordRomaji: 'e',
    wordMeaning: { en: 'picture; drawing', zh: '画；图画', zhHant: '畫；圖畫' },
    wordEmoji: '🖼️',
    kanaDistractors: ['ん', 'さ', 'そ'],
    romajiDistractors: ['i', 'ei', 'ye'],
    wordDistractors: ['そ', 'ん', 'さ'],
  }),

  お: defineHSeion({
    id: 'h-o',
    kana: 'お',
    romaji: 'o',
    kanaKanjiOrigin: '於',
    word: '青',
    wordKana: 'あお',
    wordRomaji: 'a·o',
    wordMeaning: { en: 'blue', zh: '蓝色', zhHant: '藍色' },
    wordEmoji: '🔵',
    kanaDistractors: ['あ', 'む', 'め', 'ぬ'],
    romajiDistractors: ['u', 'wo', 'ou'],
    wordDistractors: ['あぬ', 'あめ', 'おあ', 'おぬ'],
  }),

  // か行 (K-Column)
  か: defineHSeion({
    id: 'h-ka',
    kana: 'か',
    romaji: 'ka',
    kanaKanjiOrigin: '加',
    word: '赤',
    wordKana: 'あか',
    wordRomaji: 'a·ka',
    wordMeaning: { en: 'red', zh: '红色', zhHant: '紅色' },
    wordEmoji: '🔴',
    kanaDistractors: ['ケ', 'タ', 'わ'],
    romajiDistractors: ['ga', 'ki', 'ko', 'ta'],
    wordDistractors: ['あタ', 'あケ', 'おか'],
  }),

  // --- 检查到这了 ---
  き: defineHSeion({
    id: 'h-ki',
    kana: 'き',
    romaji: 'ki',
    kanaKanjiOrigin: '幾',
    word: '駅',
    wordKana: 'えき',
    wordRomaji: 'e·ki',
    wordMeaning: { en: 'station', zh: '车站', zhHant: '車站' },
    wordEmoji: '🚉',
    kanaDistractors: ['さ', 'ち', 'ぎ'],
    romajiDistractors: ['ka', 'shi', 'ke'],
    wordDistractors: ['えさ', 'えち', 'えぎ'],
  }),

  く: defineHSeion({
    id: 'h-ku',
    kana: 'く',
    romaji: 'ku',
    kanaKanjiOrigin: '久',
    word: '空気',
    wordKana: 'くうき',
    wordRomaji: 'ku·u·ki',
    wordMeaning: { en: 'air', zh: '空气', zhHant: '空氣' },
    wordEmoji: '💨',
    kanaDistractors: ['へ', 'て', 'ぐ'],
    romajiDistractors: ['ke', 'ko', 'fu'],
    wordDistractors: ['へうき', 'ぐうき', 'てうき'],
  }),

  け: defineHSeion({
    id: 'h-ke',
    kana: 'け',
    romaji: 'ke',
    kanaKanjiOrigin: '計',
    word: '池',
    wordKana: 'いけ',
    wordRomaji: 'i·ke',
    wordMeaning: { en: 'pond', zh: '池塘', zhHant: '池塘' },
    wordEmoji: '⛲',
    kanaDistractors: ['は', 'に', 'ほ'],
    romajiDistractors: ['ki', 'ku', 'he'],
    wordDistractors: ['いは', 'いに', 'いほ'],
  }),

  こ: defineHSeion({
    id: 'h-ko',
    kana: 'こ',
    romaji: 'ko',
    kanaKanjiOrigin: '己',
    word: '声',
    wordKana: 'こえ',
    wordRomaji: 'ko·e',
    wordMeaning: { en: 'voice', zh: '声音', zhHant: '聲音' },
    wordEmoji: '🗣️',
    kanaDistractors: ['い', 'に', 'た'],
    romajiDistractors: ['ka', 'ke', 'to'],
    wordDistractors: ['にえ', 'いえ', 'たえ'],
  }),

  // さ行 (S-Column)
  さ: defineHSeion({
    id: 'h-sa',
    kana: 'さ',
    romaji: 'sa',
    kanaKanjiOrigin: '左',
    word: '傘',
    wordKana: 'かさ',
    wordRomaji: 'ka·sa',
    wordMeaning: { en: 'umbrella', zh: '伞', zhHant: '傘' },
    wordEmoji: '☂️',
    kanaDistractors: ['き', 'ち', 'ざ'],
    romajiDistractors: ['shi', 'su', 'za'],
    wordDistractors: ['かき', 'かち', 'かざ'],
  }),

  し: defineHSeion({
    id: 'h-shi',
    kana: 'し',
    romaji: 'shi',
    kanaKanjiOrigin: '之',
    word: '石',
    wordKana: 'いし',
    wordRomaji: 'i·shi',
    wordMeaning: { en: 'stone', zh: '石头', zhHant: '石頭' },
    wordEmoji: '🪨',
    kanaDistractors: ['つ', 'も', 'じ'],
    romajiDistractors: ['si', 'chi', 'hi'],
    wordDistractors: ['いつ', 'いも', 'いじ'],
    noteKey: 'studyKana.notes.hshi',
  }),

  す: defineHSeion({
    id: 'h-su',
    kana: 'す',
    romaji: 'su',
    kanaKanjiOrigin: '寸',
    word: '椅子',
    wordKana: 'いす',
    wordRomaji: 'i·su',
    wordMeaning: { en: 'chair', zh: '椅子', zhHant: '椅子' },
    wordEmoji: '🪑',
    kanaDistractors: ['お', 'む', 'ず'],
    romajiDistractors: ['shu', 'so', 'zu'],
    wordDistractors: ['いお', 'いむ', 'いず'],
  }),

  せ: defineHSeion({
    id: 'h-se',
    kana: 'せ',
    romaji: 'se',
    kanaKanjiOrigin: '世',
    word: '世界',
    wordKana: 'せかい',
    wordRomaji: 'se·ka·i',
    wordMeaning: { en: 'world', zh: '世界', zhHant: '世界' },
    wordEmoji: '🌍',
    kanaDistractors: ['サ', 'や', 'ぜ'],
    romajiDistractors: ['she', 'ce', 'ze'],
    wordDistractors: ['サかい', 'やかい', 'ぜかい'],
  }),

  そ: defineHSeion({
    id: 'h-so',
    kana: 'そ',
    romaji: 'so',
    kanaKanjiOrigin: '曾',
    word: '嘘',
    wordKana: 'うそ',
    wordRomaji: 'u·so',
    wordMeaning: { en: 'lie', zh: '谎言', zhHant: '謊言' },
    wordEmoji: '🤥',
    kanaDistractors: ['ろ', 'る', 'ぞ'],
    romajiDistractors: ['sa', 'su', 'zo'],
    wordDistractors: ['うろ', 'うる', 'うぞ'],
  }),

  // た行 (T-Column)
  た: defineHSeion({
    id: 'h-ta',
    kana: 'た',
    romaji: 'ta',
    kanaKanjiOrigin: '太',
    word: '歌',
    wordKana: 'うた',
    wordRomaji: 'u·ta',
    wordMeaning: { en: 'song', zh: '歌曲', zhHant: '歌曲' },
    wordEmoji: '🎤',
    kanaDistractors: ['に', 'な', 'だ'],
    romajiDistractors: ['da', 'to', 'ka'],
    wordDistractors: ['うに', 'うな', 'うだ'],
  }),

  ち: defineHSeion({
    id: 'h-chi',
    kana: 'ち',
    romaji: 'chi',
    kanaKanjiOrigin: '知',
    word: '土',
    wordKana: 'つち',
    wordRomaji: 'tsu·chi',
    wordMeaning: { en: 'soil; earth', zh: '泥土；土地', zhHant: '泥土；土地' },
    wordEmoji: '🌱',
    kanaDistractors: ['ら', 'さ', 'ぢ'],
    romajiDistractors: ['ti', 'shi', 'ji'],
    wordDistractors: ['つら', 'つさ', 'つぢ'],
    noteKey: 'studyKana.notes.hchi',
  }),

  つ: defineHSeion({
    id: 'h-tsu',
    kana: 'つ',
    romaji: 'tsu',
    kanaKanjiOrigin: '川',
    word: '月',
    wordKana: 'つき',
    wordRomaji: 'tsu·ki',
    wordMeaning: { en: 'moon', zh: '月亮', zhHant: '月亮' },
    wordEmoji: '🌙',
    kanaDistractors: ['う', 'し', 'づ'],
    romajiDistractors: ['tu', 'su', 'zu'],
    wordDistractors: ['うき', 'つえ', 'づき', 'きつ'],
    noteKey: 'studyKana.notes.htsu',
  }),

  て: defineHSeion({
    id: 'h-te',
    kana: 'て',
    romaji: 'te',
    kanaKanjiOrigin: '天',
    word: '手',
    wordKana: 'て',
    wordRomaji: 'te',
    wordMeaning: { en: 'hand', zh: '手', zhHant: '手' },
    wordEmoji: '✋',
    kanaDistractors: ['と', 'く', 'で'],
    romajiDistractors: ['de', 'ta', 'he'],
    wordDistractors: ['と', 'く', 'で'],
  }),

  と: defineHSeion({
    id: 'h-to',
    kana: 'と',
    romaji: 'to',
    kanaKanjiOrigin: '止',
    word: '時計',
    wordKana: 'とけい',
    wordRomaji: 'to·ke·i',
    wordMeaning: { en: 'clock', zh: '钟；表', zhHant: '钟；表' },
    wordEmoji: '🕓',
    kanaDistractors: ['て', 'ど', 'を'],
    romajiDistractors: ['do', 'ta', 'so'],
    wordDistractors: ['てけい', 'そけい', 'そをい'],
  }),

  // な行 (N-Column)
  な: defineHSeion({
    id: 'h-na',
    kana: 'な',
    romaji: 'na',
    kanaKanjiOrigin: '奈',
    word: '魚',
    wordKana: 'さかな',
    wordRomaji: 'sa·ka·na',
    wordMeaning: { en: 'fish', zh: '鱼', zhHant: '魚' },
    wordEmoji: '🐟',
    kanaDistractors: ['た', 'は', 'か'],
    romajiDistractors: ['ne', 'nu', 'ma'],
    wordDistractors: ['さかた', 'さかは', 'さかま'],
  }),

  に: defineHSeion({
    id: 'h-ni',
    kana: 'に',
    romaji: 'ni',
    kanaKanjiOrigin: '仁',
    word: '国',
    wordKana: 'くに',
    wordRomaji: 'ku·ni',
    wordMeaning: { en: 'country', zh: '国家', zhHant: '國家' },
    wordEmoji: '🎌',
    kanaDistractors: ['こ', 'た', 'は'],
    romajiDistractors: ['mi', 'ne', 'li'],
    wordDistractors: ['くこ', 'くた', 'くは'],
  }),

  ぬ: defineHSeion({
    id: 'h-nu',
    kana: 'ぬ',
    romaji: 'nu',
    kanaKanjiOrigin: '奴',
    word: '犬',
    wordKana: 'いぬ',
    wordRomaji: 'i·nu',
    wordMeaning: { en: 'dog', zh: '狗', zhHant: '狗' },
    wordEmoji: '🐕',
    kanaDistractors: ['め', 'あ', 'ね'],
    romajiDistractors: ['no', 'mu', 'ne'],
    wordDistractors: ['いめ', 'いあ', 'いね'],
  }),

  ね: defineHSeion({
    id: 'h-ne',
    kana: 'ね',
    romaji: 'ne',
    kanaKanjiOrigin: '祢',
    word: '猫',
    wordKana: 'ねこ',
    wordRomaji: 'ne·ko',
    wordMeaning: { en: 'cat', zh: '猫', zhHant: '貓' },
    wordEmoji: '🐈',
    kanaDistractors: ['わ', 'れ', 'ぬ'],
    romajiDistractors: ['na', 'ni', 'me'],
    wordDistractors: ['わこ', 'れこ', 'ぬこ'],
  }),

  の: defineHSeion({
    id: 'h-no',
    kana: 'の',
    romaji: 'no',
    kanaKanjiOrigin: '乃',
    word: '布',
    wordKana: 'ぬの',
    wordRomaji: 'nu·no',
    wordMeaning: { en: 'cloth', zh: '布', zhHant: '布' },
    wordEmoji: '🧣',
    kanaDistractors: ['め', 'ぬ', 'あ'],
    romajiDistractors: ['mo', 'nu', 'na'],
    wordDistractors: ['ぬめ', 'ぬぬ', 'ぬあ'],
  }),

  // ま行 (M-Column)
  ま: defineHSeion({
    id: 'h-ma',
    kana: 'ま',
    romaji: 'ma',
    kanaKanjiOrigin: '末', // "末"的草书

    word: '豆',
    wordKana: 'まめ',
    wordRomaji: 'ma·me',
    wordMeaning: { en: 'beans', zh: '豆子', zhHant: '豆子' },

    wordEmoji: '🫘',
    kanaDistractors: ['ほ', 'は', 'よ'],
    romajiDistractors: ['mo', 'na', 'ho'],
    wordDistractors: ['ほめ', 'はめ', 'よめ'],
  }),

  み: defineHSeion({
    id: 'h-mi',
    kana: 'み',
    romaji: 'mi',
    kanaKanjiOrigin: '美',

    word: '耳',
    wordKana: 'みみ',
    wordRomaji: 'mi·mi',
    wordMeaning: { en: 'ear', zh: '耳朵', zhHant: '耳朵' },

    wordEmoji: '👂',
    kanaDistractors: ['ゐ', 'ぬ', 'ね'],
    romajiDistractors: ['ni', 'me', 'mu'],
    wordDistractors: ['ゐゐ', 'ぬぬ', 'ねね'],
  }),

  む: defineHSeion({
    id: 'h-mu',
    kana: 'む',
    romaji: 'mu',
    kanaKanjiOrigin: '武',

    word: '虫',
    wordKana: 'むし',
    wordRomaji: 'mu·shi',
    wordMeaning: { en: 'insect; bug', zh: '虫子', zhHant: '蟲子' },

    wordEmoji: '🐛',
    kanaDistractors: ['す', 'ま', 'お'],
    romajiDistractors: ['su', 'nu', 'fu'],
    wordDistractors: ['すし', 'まし', 'おし'],
  }),

  め: defineHSeion({
    id: 'h-me',
    kana: 'め',
    romaji: 'me',
    kanaKanjiOrigin: '女',

    word: '目',
    wordKana: 'め',
    wordRomaji: 'me',
    wordMeaning: { en: 'eye', zh: '眼睛', zhHant: '眼睛' },

    wordEmoji: '👁️',
    kanaDistractors: ['ぬ', 'あ', 'の'],
    romajiDistractors: ['nu', 'ne', 'ma'],
    wordDistractors: ['ぬ', 'あ', 'の'],
  }),

  も: defineHSeion({
    id: 'h-mo',
    kana: 'も',
    romaji: 'mo',
    kanaKanjiOrigin: '毛',

    word: '桃',
    wordKana: 'もも',
    wordRomaji: 'mo·mo',
    wordMeaning: { en: 'peach', zh: '桃子', zhHant: '桃子' },

    wordEmoji: '🍑',
    kanaDistractors: ['ま', 'し', 'き'],
    romajiDistractors: ['ma', 'yo', 'no'],
    wordDistractors: ['まま', 'きき', 'きも'],
  }),

  // は行 (H-Column)
  は: defineHSeion({
    id: 'h-ha',
    kana: 'は',
    romaji: 'ha',
    kanaKanjiOrigin: '波',
    word: '花',
    wordKana: 'はな',
    wordRomaji: 'ha·na',
    wordMeaning: { en: 'flower', zh: '花', zhHant: '花' },
    wordEmoji: '🌸',
    kanaDistractors: ['ほ', 'け', 'ま'],
    romajiDistractors: ['wa', 'ho', 'he'],
    wordDistractors: ['ほな', 'けな', 'まな'],
    noteKey: 'studyKana.notes.hha',
  }),

  ひ: defineHSeion({
    id: 'h-hi',
    kana: 'ひ',
    romaji: 'hi',
    kanaKanjiOrigin: '比',
    word: '人',
    wordKana: 'ひと',
    wordRomaji: 'hi·to',
    wordMeaning: { en: 'person', zh: '人', zhHant: '人' },
    wordEmoji: '👤',
    kanaDistractors: ['て', 'い', 'び'],
    romajiDistractors: ['he', 'bi', 'pi'],
    wordDistractors: ['てと', 'いと', 'びと'],
  }),

  ふ: defineHSeion({
    id: 'h-fu',
    kana: 'ふ',
    romaji: 'fu',
    kanaKanjiOrigin: '不',
    word: '船',
    wordKana: 'ふね',
    wordRomaji: 'fu·ne',
    wordMeaning: { en: 'ship; boat', zh: '船', zhHant: '船' },
    wordEmoji: '🚢',
    kanaDistractors: ['ぶ', 'ぷ', 'や'],
    romajiDistractors: ['hu', 'bu', 'pu'],
    wordDistractors: ['ぶね', 'ぷね', 'やね'],
    noteKey: 'studyKana.notes.hfu',
  }),

  へ: defineHSeion({
    id: 'h-he',
    kana: 'へ',
    romaji: 'he',
    kanaKanjiOrigin: '部',
    word: '部屋',
    wordKana: 'へや',
    wordRomaji: 'he·ya',
    wordMeaning: { en: 'room', zh: '房间', zhHant: '房間' },
    wordEmoji: '🚪',
    kanaDistractors: ['く', 'て', 'べ'],
    romajiDistractors: ['be', 'pe', 'fe'],
    wordDistractors: ['くや', 'てや', 'べや'],
    noteKey: 'studyKana.notes.hhe',
  }),

  ほ: defineHSeion({
    id: 'h-ho',
    kana: 'ほ',
    romaji: 'ho',
    kanaKanjiOrigin: '保',
    word: '星',
    wordKana: 'ほし',
    wordRomaji: 'ho·shi',
    wordMeaning: { en: 'star', zh: '星星', zhHant: '星星' },
    wordEmoji: '⭐',
    kanaDistractors: ['は', 'ま', 'ぼ'],
    romajiDistractors: ['ha', 'bo', 'po'],
    wordDistractors: ['はし', 'まし', 'ぼし'],
  }),

  // や行 (Y-Column)
  や: defineHSeion({
    id: 'h-ya',
    kana: 'や',
    romaji: 'ya',
    kanaKanjiOrigin: '也',
    word: '野菜',
    wordKana: 'やさい',
    wordRomaji: 'ya·sa·i',
    wordMeaning: { en: 'vegetable', zh: '蔬菜', zhHant: '蔬菜' },
    wordEmoji: '🥦',
    kanaDistractors: ['か', 'ま', 'せ'],
    romajiDistractors: ['yo', 'yu', 'a'],
    wordDistractors: ['かさい', 'まさい', 'せさい'],
  }),

  ゆ: defineHSeion({
    id: 'h-yu',
    kana: 'ゆ',
    romaji: 'yu',
    kanaKanjiOrigin: '由',
    word: '雪',
    wordKana: 'ゆき',
    wordRomaji: 'yu·ki',
    wordMeaning: { en: 'snow', zh: '雪', zhHant: '雪' },
    wordEmoji: '❄️',
    kanaDistractors: ['わ', 'ぬ', 'め'],
    romajiDistractors: ['yo', 'ya', 'u'],
    wordDistractors: ['わき', 'ぬき', 'めき'],
  }),

  よ: defineHSeion({
    id: 'h-yo',
    kana: 'よ',
    romaji: 'yo',
    kanaKanjiOrigin: '与',
    word: '夜',
    wordKana: 'よる',
    wordRomaji: 'yo·ru',
    wordMeaning: { en: 'night', zh: '夜晚', zhHant: '夜晚' },
    wordEmoji: '🌃',
    kanaDistractors: ['ま', 'は', 'ほ'],
    romajiDistractors: ['yu', 'ya', 'mo'],
    wordDistractors: ['まる', 'はる', 'ほる'],
  }),

  //ら行 (R-Column)
  ら: defineHSeion({
    id: 'h-ra',
    kana: 'ら',
    romaji: 'ra',
    kanaKanjiOrigin: '良',
    word: '空',
    wordKana: 'そら',
    wordRomaji: 'so·ra',
    wordMeaning: { en: 'sky', zh: '天空', zhHant: '天空' },
    wordEmoji: '☁️',
    kanaDistractors: ['ち', 'ろ', 'う'],
    romajiDistractors: ['la', 'ru', 'ro'],
    wordDistractors: ['そち', 'そろ', 'そう'],
  }),

  り: defineHSeion({
    id: 'h-ri',
    kana: 'り',
    romaji: 'ri',
    kanaKanjiOrigin: '利',
    word: '鳥',
    wordKana: 'とり',
    wordRomaji: 'to·ri',
    wordMeaning: { en: 'bird', zh: '鸟', zhHant: '鳥' },
    wordEmoji: '🐦',
    kanaDistractors: ['い', 'け', 'こ'],
    romajiDistractors: ['li', 'ry', 'i'],
    wordDistractors: ['とい', 'とけ', 'とこ'],
  }),

  る: defineHSeion({
    id: 'h-ru',
    kana: 'る',
    romaji: 'ru',
    kanaKanjiOrigin: '留',
    word: '猿',
    wordKana: 'さる',
    wordRomaji: 'sa·ru',
    wordMeaning: { en: 'monkey', zh: '猴子', zhHant: '猴子' },
    wordEmoji: '🐒',
    kanaDistractors: ['ろ', 'そ', 'ゐ'],
    romajiDistractors: ['lu', 'ro', 'zu'],
    wordDistractors: ['さろ', 'さそ', 'さゐ'],
  }),

  れ: defineHSeion({
    id: 'h-re',
    kana: 'れ',
    romaji: 're',
    kanaKanjiOrigin: '礼',
    word: '晴れ',
    wordKana: 'はれ',
    wordRomaji: 'ha·re',
    wordMeaning: { en: 'sunny', zh: '晴天', zhHant: '晴天' },
    wordEmoji: '☀️',
    kanaDistractors: ['ね', 'わ', 'め'],
    romajiDistractors: ['le', 'ne', 'wa'],
    wordDistractors: ['はね', 'はわ', 'はめ'],
  }),

  ろ: defineHSeion({
    id: 'h-ro',
    kana: 'ろ',
    romaji: 'ro',
    kanaKanjiOrigin: '呂',
    word: '色',
    wordKana: 'いろ',
    wordRomaji: 'i·ro',
    wordMeaning: { en: 'color', zh: '颜色', zhHant: '顏色' },
    wordEmoji: '🎨',
    kanaDistractors: ['る', 'そ', 'あ'],
    romajiDistractors: ['lo', 'ru', 'so'],
    wordDistractors: ['いる', 'いそ', 'いあ'],
  }),

  // わ行 (W-Column) & ん (N)
  わ: defineHSeion({
    id: 'h-wa',
    kana: 'わ',
    romaji: 'wa',
    kanaKanjiOrigin: '和',
    word: '川',
    wordKana: 'かわ',
    wordRomaji: 'ka·wa',
    wordMeaning: { en: 'river', zh: '河流', zhHant: '河流' },
    wordEmoji: '🏞️',
    kanaDistractors: ['ね', 'れ', 'ぬ'],
    romajiDistractors: ['ha', 'ma', 'ra'],
    wordDistractors: ['かね', 'かれ', 'かぬ'],
  }),

  を: defineHSeion({
    id: 'h-wo',
    kana: 'を',
    romaji: 'wo',
    kanaKanjiOrigin: '遠',

    // 🔥 を 无法组词，word 相关字段都不填，
    //  在 lessonlogic 里会自动跳过

    // word: '本を', // 助词示例
    // wordKana: 'ほんを',
    // wordRomaji: 'hon·o',
    // wordMeaning: {
    //   en: '(object marker)',
    //   zh: '把/将(助词)',
    //   zhHant: '把/將(助詞)',
    // },
    // wordDistractors: ['ほんと', 'ほんち', 'ほんさ'],
    // wordEmoji: '📖',

    kanaDistractors: ['わ', 'ね', 'れ'],
    romajiDistractors: ['wa', 'on', 'o'],
    noteKey: 'studyKana.notes.hwo',
  }),

  ん: defineHSeion({
    id: 'h-n',
    kana: 'ん',
    romaji: 'n',
    kanaKanjiOrigin: '无',
    word: '本',
    wordKana: 'ほん',
    wordRomaji: 'ho·n',
    wordMeaning: { en: 'book', zh: '书', zhHant: '書' },
    wordEmoji: '📚',
    kanaDistractors: ['そ', 'え', 'し'],
    romajiDistractors: ['en', 'ng', 'on'],
    wordDistractors: ['ほそ', 'ほえ', 'ほし'],
  }),

  // --- 特殊例子：wo (无单词) ---
  // 按照您的要求，处理这种“扩展难”的特殊情况
  // を: defineHSeion({
  //   id: 'h-wo',
  //   kana: 'を',
  //   romaji: 'wo',
  //   kanaKanjiOrigin: '遠',

  //   // ✅ 关键改变：这里我们不填 word 字段
  //   // 这真实地反映了数据状态。Logic 层看到没有 word，就不会生成单词卡。
  //   // 从而避免了旧代码里 word: 'を' 这种为了不报错而填的占位符。
  //   noteKey: 'studyKana.notes.wo', // 保留 noteKey

  //   kanaDistractors: ['わ', 'ね', 'れ'],
  //   romajiDistractors: ['wa', 'on', 'o'],
  // }),
};
