export interface DateItem {
  id: number;
  kanji: string;
  kana: string;
  romaji: string;
  isIrregular: boolean; // 是否是不规则读音 (难点)
}

export const datesData: DateItem[] = [
  {
    id: 1,
    kanji: '一日',
    kana: 'ついたち',
    romaji: 'tsu·i·ta·chi',
    isIrregular: true,
  },
  {
    id: 2,
    kanji: '二日',
    kana: 'ふつか',
    romaji: 'fu·tsu·ka',
    isIrregular: true,
  },
  {
    id: 3,
    kanji: '三日',
    kana: 'みっか',
    romaji: 'mi·k·ka',
    isIrregular: true,
  },
  {
    id: 4,
    kanji: '四日',
    kana: 'よっか',
    romaji: 'yo·k·ka',
    isIrregular: true,
  },
  {
    id: 5,
    kanji: '五日',
    kana: 'いつか',
    romaji: 'i·tsu·ka',
    isIrregular: true,
  },
  {
    id: 6,
    kanji: '六日',
    kana: 'むいか',
    romaji: 'mu·i·ka',
    isIrregular: true,
  },
  {
    id: 7,
    kanji: '七日',
    kana: 'なのか',
    romaji: 'na·no·ka',
    isIrregular: true,
  },
  {
    id: 8,
    kanji: '八日',
    kana: 'ようか',
    romaji: 'yo·u·ka',
    isIrregular: true,
  },
  {
    id: 9,
    kanji: '九日',
    kana: 'ここのか',
    romaji: 'ko·ko·no·ka',
    isIrregular: true,
  },
  {
    id: 10,
    kanji: '十日',
    kana: 'とおか',
    romaji: 'to·o·ka',
    isIrregular: true,
  },
  {
    id: 11,
    kanji: '十一日',
    kana: 'じゅういちにち',
    romaji: 'ju·u·i·chi·ni·chi',
    isIrregular: false,
  },
  {
    id: 12,
    kanji: '十二日',
    kana: 'じゅうににち',
    romaji: 'ju·u·ni·ni·chi',
    isIrregular: false,
  },
  {
    id: 13,
    kanji: '十三日',
    kana: 'じゅうさんにち',
    romaji: 'ju·u·sa·n·ni·chi',
    isIrregular: false,
  },
  {
    id: 14,
    kanji: '十四日',
    kana: 'じゅうよっか',
    romaji: 'ju·u·yo·k·ka',
    isIrregular: true,
  }, // Irregular
  {
    id: 15,
    kanji: '十五日',
    kana: 'じゅうごにち',
    romaji: 'ju·u·go·ni·chi',
    isIrregular: false,
  },
  {
    id: 16,
    kanji: '十六日',
    kana: 'じゅうろくにち',
    romaji: 'ju·u·ro·ku·ni·chi',
    isIrregular: false,
  },
  {
    id: 17,
    kanji: '十七日',
    kana: 'じゅうしちにち',
    romaji: 'ju·u·shi·chi·ni·chi',
    isIrregular: false,
  },
  {
    id: 18,
    kanji: '十八日',
    kana: 'じゅうはちにち',
    romaji: 'ju·u·ha·chi·ni·chi',
    isIrregular: false,
  },
  {
    id: 19,
    kanji: '十九日',
    kana: 'じゅうくにち',
    romaji: 'ju·u·ku·ni·chi',
    isIrregular: false,
  },
  {
    id: 20,
    kanji: '二十日',
    kana: 'はつか',
    romaji: 'ha·tsu·ka',
    isIrregular: true,
  }, // Super Irregular
  {
    id: 21,
    kanji: '二十一日',
    kana: 'にじゅういちにち',
    romaji: 'ni·ju·u·i·chi·ni·chi',
    isIrregular: false,
  },
  {
    id: 22,
    kanji: '二十二日',
    kana: 'にじゅうににち',
    romaji: 'ni·ju·u·ni·ni·chi',
    isIrregular: false,
  },
  {
    id: 23,
    kanji: '二十三日',
    kana: 'にじゅうさんにち',
    romaji: 'ni·ju·u·sa·n·ni·chi',
    isIrregular: false,
  },
  {
    id: 24,
    kanji: '二十四日',
    kana: 'にじゅうよっか',
    romaji: 'ni·ju·u·yo·k·ka',
    isIrregular: true,
  }, // Irregular
  {
    id: 25,
    kanji: '二十五日',
    kana: 'にじゅうごにち',
    romaji: 'ni·ju·u·go·ni·chi',
    isIrregular: false,
  },
  {
    id: 26,
    kanji: '二十六日',
    kana: 'にじゅうろくにち',
    romaji: 'ni·ju·u·ro·ku·ni·chi',
    isIrregular: false,
  },
  {
    id: 27,
    kanji: '二十七日',
    kana: 'にじゅうしちにち',
    romaji: 'ni·ju·u·shi·chi·ni·chi',
    isIrregular: false,
  },
  {
    id: 28,
    kanji: '二十八日',
    kana: 'にじゅうはちにち',
    romaji: 'ni·ju·u·ha·chi·ni·chi',
    isIrregular: false,
  },
  {
    id: 29,
    kanji: '二十九日',
    kana: 'にじゅうくにち',
    romaji: 'ni·ju·u·ku·ni·chi',
    isIrregular: false,
  },
  {
    id: 30,
    kanji: '三十日',
    kana: 'さんじゅうにち',
    romaji: 'sa·n·ju·u·ni·chi',
    isIrregular: false,
  },
  {
    id: 31,
    kanji: '三十一日',
    kana: 'さんじゅういちにち',
    romaji: 'sa·n·ju·u·i·chi·ni·chi',
    isIrregular: false,
  },
];
