export interface LocalizedText {
  en: string;
  zh: string;
}

export interface KanaEntry {
  char: string;
  romaji: string;
  word: string;
  wordRomaji: string;
  kanji: string;
  kanjiOrigin?: string;
  noteKey?: string;
  meaning: LocalizedText;
  // 保持宽松定义，让 defineKana 处理严格校验
  romajiDistractors: readonly string[];
  charDistractors: readonly string[];
  wordDistractors: readonly string[];
}

// --- 点对点精准验证器 ---
/**
 * 这是一个映射类型 (Mapped Type)。
 * 它会遍历 Distractors 数组里的每一项 [K in keyof Distractors]。
 * * 逻辑：
 * 1. 先检查数组总长度。如果不合法，返回一个整体报错的类型。
 * 2. 如果长度合法，逐个检查元素：
 * - 如果该元素 == Answer，把它的类型强制变成一个只有报错信息的字符串字面量。
 * - 否则，保持它原来的类型。
 */
type PreciseValidator<
  Distractors extends readonly string[],
  Answer extends string,
> =
  // 检查长度
  Distractors['length'] extends 3 | 4 | 5 | 6
    ? {
        // 遍历每一项
        [K in keyof Distractors]: Distractors[K] extends Answer
          ? '❌ 错误：不能包含正确答案' // 👈 只有撞车的这一项会变成这个类型，导致报错
          : Distractors[K]; // 👈 其他项保持原样
      }
    : readonly ['❌ 错误：干扰项数量必须在 3 到 6 个之间']; // 长度错误依然报在整体上

// --- 3. 构造函数 defineKana ---

const defineKana = <
  const C extends string,
  const R extends string,
  const W extends string,
  const RD extends readonly string[],
  const CD extends readonly string[],
  const WD extends readonly string[],
>(data: {
  char: C;
  romaji: R;
  word: W;
  wordRomaji: string;
  kanji: string;
  meaning: LocalizedText;
  kanjiOrigin?: string;
  noteKey?: string;

  romajiDistractors: PreciseValidator<RD, R>;
  charDistractors: PreciseValidator<CD, C>;
  wordDistractors: PreciseValidator<WD, W>;
}): KanaEntry => {
  // 强转返回，因为 PreciseValidator 产生的类型在运行时其实就是 string[]
  return data as unknown as KanaEntry;
};

export const KANA_DB: Record<string, KanaEntry> = {
  あ: defineKana({
    char: 'あ',
    kanjiOrigin: '安',
    romaji: 'a',
    word: 'あい',
    wordRomaji: 'a·i',
    kanji: '愛',
    meaning: {
      en: 'love',
      zh: '爱',
    },
    romajiDistractors: ['o', 'ou', 'au'],
    charDistractors: ['お', 'め', 'ぬ'],
    wordDistractors: ['あり', 'ぬい', 'めい'],
  }),
  い: defineKana({
    char: 'い',
    kanjiOrigin: '以',
    romaji: 'i',
    word: 'いえ',
    wordRomaji: 'i·e',
    kanji: '家',
    meaning: { en: 'family; house', zh: '房子；家' },
    romajiDistractors: ['e', 'ei', 'ie'],
    charDistractors: ['り', 'こ', 'に'],
    wordDistractors: ['りえ', 'いう', 'いら', 'こえ'],
  }),
  う: defineKana({
    char: 'う',
    kanjiOrigin: '宇',
    romaji: 'u',
    word: 'うえ',
    wordRomaji: 'u·e',
    kanji: '上',
    meaning: { en: 'up; superior', zh: '上面' },
    romajiDistractors: ['wu', 'eu', 'ui'],
    charDistractors: ['え', 'ラ', 'ら'],
    wordDistractors: ['うら', 'えう', 'ラら', 'ラえ'],
  }),
  え: defineKana({
    char: 'え',
    kanjiOrigin: '衣',
    charDistractors: ['う', 'ラ', 'ら'],
    romaji: 'e',
    romajiDistractors: ['wu', 'eu', 'ui'],
    word: 'えき',
    wordRomaji: 'e·ki',
    kanji: '駅',
    meaning: { en: '(train) station', zh: '车站' },
    wordDistractors: ['あき', 'うき', 'ラき', 'ラえ', 'えさ', 'ラさ'],
  }),
  お: defineKana({
    char: 'お',
    kanjiOrigin: '於',
    charDistractors: ['あ', 'む', 'す'],
    romaji: 'o',
    romajiDistractors: ['ou', 'uo', 'wo'],
    kanji: '青い',
    word: 'あおい',
    wordRomaji: 'a·o·i',
    meaning: { en: 'blue; green', zh: '蓝色；年轻的' },
    wordDistractors: ['あさい', 'おさい', 'おあい'],
  }),
  か: defineKana({
    char: 'か',
    kanjiOrigin: '加',
    charDistractors: ['が', 'や', 'わ'],
    romaji: 'ka',
    romajiDistractors: ['ga', 'ko', 'kya'],
    kanji: '赤い',
    word: 'あかい',
    wordRomaji: 'a·ka·i',
    meaning: { en: 'red', zh: '红色的；革命的' },
    wordDistractors: ['あがい', 'おかい', 'あやい'],
  }),
  き: defineKana({
    char: 'き',
    kanjiOrigin: '幾',
    charDistractors: ['ぎ', 'さ', 'ち'],
    romaji: 'ki',
    romajiDistractors: ['gi', 'ky', 'ke'],
    kanji: '秋',
    word: 'あき',
    wordRomaji: 'a·ki',
    meaning: { en: 'autumn; fall', zh: '秋季；秋天' },
    wordDistractors: ['あさ', 'あぎ', 'おき'],
  }),
  く: defineKana({
    char: 'く',
    kanjiOrigin: '久',
    charDistractors: ['ぐ', 'へ', 'し'],
    romaji: 'ku',
    romajiDistractors: ['gu', 'qu', 'ko'],
    kanji: '靴',
    word: 'くつ',
    wordRomaji: 'ku·tsu',
    meaning: { en: 'boots; shoes', zh: '鞋；靴子' },
    wordDistractors: ['ぐつ', 'へつ', 'しつ'],
  }),
  け: defineKana({
    char: 'け',
    kanjiOrigin: '計',
    charDistractors: ['げ', 'は', 'に'],
    romaji: 'ke',
    romajiDistractors: ['ge', 'ki', 'ka'],
    kanji: '池',
    word: 'いけ',
    wordRomaji: 'i·ke',
    meaning: { en: 'pond', zh: '池塘；水池' },
    wordDistractors: ['いげ', 'いは', 'りけ'],
  }),
  こ: defineKana({
    char: 'こ',
    kanjiOrigin: '己',
    charDistractors: ['ご', 'に', 'て'],
    romaji: 'ko',
    romajiDistractors: ['go', 'kou', 'ka'],
    kanji: '猫',
    word: 'ねこ',
    wordRomaji: 'ne·ko',
    meaning: { en: 'cat', zh: '猫' },
    wordDistractors: ['ねご', 'ぬこ', 'ねに'],
  }),
  さ: defineKana({
    char: 'さ',
    kanjiOrigin: '左',
    charDistractors: ['き', 'ち', 'ざ'],
    romaji: 'sa',
    romajiDistractors: ['zo', 'so', 'ki', 'so'],
    kanji: '傘',
    word: 'かさ',
    wordRomaji: 'ka·sa',
    meaning: { en: 'umbrella', zh: '伞；伞状物' },
    wordDistractors: ['かざ', 'かき', 'がさ'],
  }),
  し: defineKana({
    char: 'し',
    kanjiOrigin: '之',
    charDistractors: ['つ', 'も', 'じ'],
    romaji: 'shi',
    noteKey: 'studyKana.notes.shi',
    romajiDistractors: ['si', 'ji', 'chi'],
    kanji: '牛',
    word: 'うし',
    wordRomaji: 'u·shi',
    meaning: { en: 'cattle', zh: '牛' },
    wordDistractors: ['うじ', 'うつ', 'おし'],
  }),
  す: defineKana({
    char: 'す',
    kanjiOrigin: '寸',
    charDistractors: ['む', 'ぬ', 'ず'],
    romaji: 'su',
    romajiDistractors: ['zu', 'si', 'cu', 'ci'],
    kanji: '寿司',
    word: 'すし',
    wordRomaji: 'su·shi',
    meaning: { en: 'sushi', zh: '寿司' },
    wordDistractors: ['ずし', 'すじ', 'さし'],
  }),
  せ: defineKana({
    char: 'せ',
    kanjiOrigin: '世',
    charDistractors: ['サ', 'ぜ', 'や'],
    romaji: 'se',
    romajiDistractors: ['ze', 'sa', 'she', 'ci'],
    kanji: '汗',
    word: 'あせ',
    wordRomaji: 'a·se',
    meaning: { en: 'sweat', zh: '汗水；汗液' },
    wordDistractors: ['あぜ', 'あさ', 'おせ'],
  }),
  そ: defineKana({
    char: 'そ',
    kanjiOrigin: '曾',
    charDistractors: ['ぞ', 'ろ', 'て'],
    romaji: 'so',
    romajiDistractors: ['zo', 'zo', 'no'],
    kanji: '空',
    word: 'そら',
    wordRomaji: 'so·ra',
    meaning: { en: 'sky; air', zh: '天空；上空' },
    wordDistractors: ['ぞら', 'さら', 'そろ'],
  }),
  // --- た行 (TA) ---
  た: defineKana({
    char: 'た',
    kanjiOrigin: '太',
    charDistractors: ['だ', 'な', 'に'],
    romaji: 'ta',
    romajiDistractors: ['da', 'na', 'to'],
    kanji: '歌',
    word: 'うた',
    wordRomaji: 'u·ta',
    meaning: { en: 'song', zh: '歌；歌曲' },
    wordDistractors: ['うだ', 'うな', 'うに'],
  }),
  ち: defineKana({
    char: 'ち',
    kanjiOrigin: '知',
    charDistractors: ['ぢ', 'さ', 'ら'],
    romaji: 'chi',
    romajiDistractors: ['ti', 'shi', 'ji'],
    kanji: '口',
    word: 'くち',
    noteKey: 'studyKana.notes.chi',
    wordRomaji: 'ku·chi',
    meaning: { en: 'mouth', zh: '嘴巴' },
    wordDistractors: ['くじ', 'ぐち', 'くら'],
  }),
  つ: defineKana({
    char: 'つ',
    kanjiOrigin: '川',
    charDistractors: ['づ', 'す', 'ぬ'],
    romaji: 'tsu',
    noteKey: 'studyKana.notes.tsu',
    romajiDistractors: ['tu', 'su', 'chu'],
    kanji: '地下鉄',
    word: 'ちかてつ',
    wordRomaji: 'chi·ka·te·tsu',
    meaning: { en: 'subway', zh: '地铁' },
    wordDistractors: ['ちかてづ', 'ちかてす', 'さかてつ'],
  }),
  て: defineKana({
    char: 'て',
    kanjiOrigin: '天',
    charDistractors: ['で', 'と', 'そ'],
    romaji: 'te',
    romajiDistractors: ['de', 'ta', 'the'],
    kanji: '手',
    word: 'て',
    wordRomaji: 'te',
    meaning: { en: 'hand', zh: '手' },
    wordDistractors: ['で', 'と', 'け'],
  }),
  と: defineKana({
    char: 'と',
    kanjiOrigin: '止',
    charDistractors: ['ど', 'て', 'を'],
    romaji: 'to',
    romajiDistractors: ['do', 'tu', 'ta'],
    kanji: '時計',
    word: 'とけい',
    wordRomaji: 'to·ke·i',
    meaning: { en: 'watch; clock', zh: '钟表' },
    wordDistractors: ['どけい', 'てけい', 'たけい'],
  }),

  // --- な行 (NA) ---
  な: defineKana({
    char: 'な',
    kanjiOrigin: '奈',
    charDistractors: ['た', 'ぬ', 'ね'],
    romaji: 'na',
    romajiDistractors: ['ma', 'ha', 'da'],
    kanji: '夏',
    word: 'なつ',
    wordRomaji: 'na·tsu',
    meaning: { en: 'summer', zh: '夏天' },
    wordDistractors: ['はつ', 'ぬつ', 'なす'],
  }),
  に: defineKana({
    char: 'に',
    kanjiOrigin: '仁',
    charDistractors: ['こ', 'た', 'け'],
    romaji: 'ni',
    romajiDistractors: ['mi', 'ne', 'ri'],
    kanji: '肉',
    word: 'にく',
    wordRomaji: 'ni·ku',
    meaning: { en: 'meat', zh: '肉' },
    wordDistractors: ['りく', 'みく', 'にぐ'],
  }),
  ぬ: defineKana({
    char: 'ぬ',
    kanjiOrigin: '奴',
    charDistractors: ['め', 'ね', 'の'],
    romaji: 'nu',
    romajiDistractors: ['mu', 'ne', 'no'],
    kanji: '犬',
    word: 'いぬ',
    wordRomaji: 'i·nu',
    meaning: { en: 'dog', zh: '狗' },
    wordDistractors: ['いめ', 'いね', 'りぬ'],
  }),
  ね: defineKana({
    char: 'ね',
    kanjiOrigin: '祢',
    charDistractors: ['れ', 'わ', 'ぬ'],
    romaji: 'ne',
    romajiDistractors: ['re', 'nu', 'me'],
    kanji: '船',
    word: 'ふね',
    wordRomaji: 'fu·ne',
    meaning: { en: 'ship; boat', zh: '船' },
    wordDistractors: ['ふれ', 'ふわ', 'ふぬ', 'ふめ'],
  }),
  の: defineKana({
    char: 'の',
    kanjiOrigin: '乃',
    charDistractors: ['め', 'ぬ', 'あ'],
    romaji: 'no',
    romajiDistractors: ['mo', 'nu', 'o'],
    kanji: '飲み物',
    word: 'のみもの',
    wordRomaji: 'no·mi·mo·no',
    meaning: { en: 'beverage', zh: '饮料' },
    wordDistractors: ['めみもの', 'ぬみもの', 'のむもの'],
  }),

  // --- は行 (HA) ---
  は: defineKana({
    char: 'は',
    kanjiOrigin: '波',
    charDistractors: ['ほ', 'ば', 'ぱ'],
    romaji: 'ha',
    romajiDistractors: ['wa', 'ba', 'fa'],
    kanji: '花',
    word: 'はな',
    wordRomaji: 'ha·na',
    noteKey: 'studyKana.notes.ha',
    meaning: { en: 'flower', zh: '花' },
    wordDistractors: ['ほな', 'ばな', 'はた'],
  }),
  ひ: defineKana({
    char: 'ひ',
    kanjiOrigin: '比',
    charDistractors: ['び', 'ぴ', 'り'],
    romaji: 'hi',
    romajiDistractors: ['bi', 'pi', 'he'],
    kanji: '人',
    word: 'ひと',
    wordRomaji: 'hi·to',
    meaning: { en: 'person', zh: '人' },
    wordDistractors: ['びと', 'りと', 'ひど'],
  }),
  ふ: defineKana({
    char: 'ふ',
    kanjiOrigin: '不',
    charDistractors: ['ぶ', 'ぷ', 'う'],
    romaji: 'fu',
    noteKey: 'studyKana.notes.fu',
    romajiDistractors: ['hu', 'bu', 'pu'],
    kanji: '冬',
    word: 'ふゆ',
    wordRomaji: 'fu·yu',
    meaning: { en: 'winter', zh: '冬天' },
    wordDistractors: ['ぶゆ', 'うゆ', 'ふよ'],
  }),
  へ: defineKana({
    char: 'へ',
    kanjiOrigin: '部',
    charDistractors: ['べ', 'ぺ', 'く'],
    romaji: 'he',
    romajiDistractors: ['be', 'e', 'pe'],
    kanji: '部屋',
    noteKey: 'studyKana.notes.he',
    word: 'へや',
    wordRomaji: 'he·ya',
    meaning: { en: 'room', zh: '房间' },
    wordDistractors: ['べや', 'ぺや', 'ひや'],
  }),
  ほ: defineKana({
    char: 'ほ',
    kanjiOrigin: '保',
    charDistractors: ['は', 'ぼ', 'ぽ'],
    romaji: 'ho',
    romajiDistractors: ['bo', 'o', 'ha'],
    kanji: '星',
    word: 'ほし',
    wordRomaji: 'ho·shi',
    meaning: { en: 'star', zh: '星星' },
    wordDistractors: ['ぼし', 'はし', 'ほじ'],
  }),

  // --- ま行 (MA) ---
  ま: defineKana({
    char: 'ま',
    kanjiOrigin: '末',
    charDistractors: ['ほ', 'は', 'よ'],
    romaji: 'ma',
    romajiDistractors: ['mo', 'ha', 'na'],
    kanji: '窓',
    word: 'まど',
    wordRomaji: 'ma·do',
    meaning: { en: 'window', zh: '窗户' },
    wordDistractors: ['ほど', 'はど', 'まと'],
  }),
  み: defineKana({
    char: 'み',
    kanjiOrigin: '美',
    charDistractors: ['に', 'り', 'ほ'],
    romaji: 'mi',
    romajiDistractors: ['ni', 'me', 'hi'],
    kanji: '耳',
    word: 'みみ',
    wordRomaji: 'mi·mi',
    meaning: { en: 'ear', zh: '耳朵' },
    wordDistractors: ['にに', 'りり', 'ひひ'],
  }),
  む: defineKana({
    char: 'む',
    kanjiOrigin: '武',
    charDistractors: ['す', 'お', 'ぬ'],
    romaji: 'mu',
    romajiDistractors: ['nu', 'mo', 'bu'],
    kanji: '虫',
    word: 'むし',
    wordRomaji: 'mu·shi',
    meaning: { en: 'insect', zh: '昆虫' },
    wordDistractors: ['すし', 'ぬし', 'むじ'],
  }),
  め: defineKana({
    char: 'め',
    kanjiOrigin: '女',
    charDistractors: ['ぬ', 'の', 'ね'],
    romaji: 'me',
    romajiDistractors: ['ne', 'nu', 'mi'],
    kanji: '眼鏡',
    word: 'めがね',
    wordRomaji: 'me·ga·ne',
    meaning: { en: 'glasses', zh: '眼镜' },
    wordDistractors: ['ぬがね', 'めかね', 'めがれ'],
  }),
  も: defineKana({
    char: 'も',
    kanjiOrigin: '毛',
    charDistractors: ['ま', 'し', 'を'],
    romaji: 'mo',
    romajiDistractors: ['mu', 'no', 'ma'],
    kanji: '森',
    word: 'もり',
    wordRomaji: 'mo·ri',
    meaning: { en: 'forest', zh: '森林' },
    wordDistractors: ['めり', 'むり', 'まり'],
  }),

  // --- や、ら、わ行 (YA, RA, WA, N) ---
  や: defineKana({
    char: 'や',
    kanjiOrigin: '也',
    charDistractors: ['せ', 'か', 'わ'],
    romaji: 'ya',
    romajiDistractors: ['ia', 'ye', 'ha'],
    kanji: '山',
    word: 'やま',
    wordRomaji: 'ya·ma',
    meaning: { en: 'mountain', zh: '山' },
    wordDistractors: ['さま', 'かま', 'やわ'],
  }),
  ゆ: defineKana({
    char: 'ゆ',
    kanjiOrigin: '由',
    charDistractors: ['よ', 'ふ', 'あ'],
    romaji: 'yu',
    romajiDistractors: ['iu', 'yo', 'u'],
    kanji: '雪',
    word: 'ゆき',
    wordRomaji: 'yu·ki',
    meaning: { en: 'snow', zh: '雪' },
    wordDistractors: ['よき', 'ふき', 'うき'],
  }),
  よ: defineKana({
    char: 'よ',
    kanjiOrigin: '与',
    charDistractors: ['ゆ', 'ま', 'ほ'],
    romaji: 'yo',
    romajiDistractors: ['io', 'yu', 'o'],
    kanji: '夜',
    word: 'よる',
    wordRomaji: 'yo·ru',
    meaning: { en: 'night', zh: '夜晚' },
    wordDistractors: ['ゆる', 'まる', 'よろ'],
  }),
  ら: defineKana({
    char: 'ら',
    kanjiOrigin: '良',
    charDistractors: ['う', 'ち', 'ろ'],
    romaji: 'ra',
    romajiDistractors: ['la', 'da', 'na'],
    kanji: '空',
    word: 'そら',
    wordRomaji: 'so·ra',
    meaning: { en: 'sky', zh: '天空' },
    wordDistractors: ['さら', 'そり', 'そわ'],
  }),
  り: defineKana({
    char: 'り',
    kanjiOrigin: '利',
    charDistractors: ['い', 'に', 'け'],
    romaji: 'ri',
    romajiDistractors: ['li', 'ni', 'i'],
    kanji: '林檎',
    word: 'りんご',
    wordRomaji: 'ri·n·go',
    meaning: { en: 'apple', zh: '苹果' },
    wordDistractors: ['にんご', 'いんご', 'りんこ'],
  }),
  る: defineKana({
    char: 'る',
    kanjiOrigin: '留',
    charDistractors: ['ろ', 'ら', 'わ'],
    romaji: 'ru',
    romajiDistractors: ['lu', 'ro', 'du'],
    kanji: '猿',
    word: 'さる',
    wordRomaji: 'sa·ru',
    meaning: { en: 'monkey', zh: '猴子' },
    wordDistractors: ['さろ', 'さら', 'さわ'],
  }),
  れ: defineKana({
    char: 'れ',
    kanjiOrigin: '礼',
    charDistractors: ['ね', 'わ', 'め'],
    romaji: 're',
    romajiDistractors: ['le', 'ne', 'me'],
    kanji: '晴れ',
    word: 'はれ',
    wordRomaji: 'ha·re',
    meaning: { en: 'sunny', zh: '晴天' },
    wordDistractors: ['はね', 'はわ', 'はめ'],
  }),
  ろ: defineKana({
    char: 'ろ',
    kanjiOrigin: '呂',
    charDistractors: ['る', 'ら', 'わ'],
    romaji: 'ro',
    romajiDistractors: ['lo', 'ru', 'o'],
    kanji: '色',
    word: 'いろ',
    wordRomaji: 'i·ro',
    meaning: { en: 'color', zh: '颜色' },
    wordDistractors: ['いる', 'いら', 'いお'],
  }),
  わ: defineKana({
    char: 'わ',
    kanjiOrigin: '和',
    charDistractors: ['ね', 'れ', 'を'],
    romaji: 'wa',
    romajiDistractors: ['ha', 'ba', 'ua'],
    kanji: '川',
    word: 'かわ',
    wordRomaji: 'ka·wa',
    meaning: { en: 'river', zh: '河流' },
    wordDistractors: ['かね', 'かれ', 'わか'],
  }),
  を: defineKana({
    char: 'を',
    kanjiOrigin: '遠',
    charDistractors: ['お', 'わ', 'と'],
    romaji: 'wo',
    romajiDistractors: ['o', 'u', 'ho'],
    kanji: 'を',
    word: 'を',
    wordRomaji: 'wo',
    meaning: { en: 'object marker', zh: '助词（宾格）' },
    noteKey: 'studyKana.notes.wo',
    wordDistractors: ['お', 'わ', 'え'],
  }),
  ん: defineKana({
    char: 'ん',
    kanjiOrigin: '无',
    charDistractors: ['と', 'ソ', 'り'],
    romaji: 'n',
    romajiDistractors: ['m', 'ng', 'nn'],
    kanji: '本',
    word: 'ほん',
    wordRomaji: 'ho·n',
    meaning: { en: 'book', zh: '书' },
    wordDistractors: ['ほわ', 'ほり', 'ほも'],
  }),

  // -------- 片假名 ------- 片假名 ----- 片假名 ----- 片假名 ----- 片假名 ----- 片假名 -----

  // --- A 行  ---
  ア: defineKana({
    char: 'ア',
    kanjiOrigin: '阿',
    romaji: 'a',
    word: 'アイス',
    wordRomaji: 'a·i·su',
    kanji: 'アイス',
    meaning: {
      en: 'ice; ice cream',
      zh: '冰；冰激凌',
    },
    romajiDistractors: ['o', 'u', 'e'],
    charDistractors: ['マ', 'ヤ', 'イ'],
    wordDistractors: ['マイス', 'ヤイス', 'アイヌ'],
  }),
  イ: defineKana({
    char: 'イ',
    kanjiOrigin: '伊',
    romaji: 'i',
    word: 'インク',
    wordRomaji: 'i·n·ku',
    kanji: 'インク',
    meaning: {
      en: 'ink',
      zh: '墨水',
    },
    romajiDistractors: ['e', 'u', 'a'],
    charDistractors: ['ア', 'ト', 'ニ'],
    wordDistractors: ['アンク', 'ウンク', 'イソク'],
  }),
  ウ: defineKana({
    char: 'ウ',
    kanjiOrigin: '宇',
    romaji: 'u',
    word: 'ウエスト',
    wordRomaji: 'u·e·su·to',
    kanji: 'ウエスト',
    meaning: {
      en: 'waist; west',
      zh: '腰部；西方',
    },
    romajiDistractors: ['o', 'a', 'e'],
    charDistractors: ['ワ', 'ラ', 'フ'],
    wordDistractors: ['ワエスト', 'ラエスト', 'ウイスト'],
  }),
  エ: defineKana({
    char: 'エ',
    kanjiOrigin: '江',
    romaji: 'e',
    word: 'エアコン',
    wordRomaji: 'e·a·ko·n',
    kanji: 'エアコン',
    meaning: {
      en: 'air conditioner',
      zh: '空调',
    },
    romajiDistractors: ['i', 'a', 'o'],
    charDistractors: ['工', 'ユ', 'コ'],
    wordDistractors: ['ユアコン', 'コアコン', 'エアドン'],
  }),
  オ: defineKana({
    char: 'オ',
    kanjiOrigin: '於',
    romaji: 'o',
    word: 'オレンジ',
    wordRomaji: 'o·re·n·ji',
    kanji: 'オレンジ',
    meaning: {
      en: 'orange',
      zh: '橙子；橙色',
    },
    romajiDistractors: ['a', 'u', 'e'],
    charDistractors: ['ホ', 'ナ', 'メ'],
    wordDistractors: ['ナレンジ', 'ホレンジ', 'オレソジ'],
  }),
};
